# Generated by Django 5.0.6 on 2024-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loandata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('sur_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pancard', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pincode', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('empoyement_type', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('ref_contact', models.CharField(max_length=15)),
                ('f_name', models.CharField(max_length=100)),
                ('m_status', models.CharField(max_length=100)),
                ('f_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
