# Generated by Django 5.0.6 on 2024-07-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loandata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandata',
            name='dob',
        ),
    ]
