# Generated by Django 5.0.6 on 2024-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandata', '0002_remove_loandata_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandata',
            name='monthly_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
