# Generated by Django 5.0.6 on 2024-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loandata', '0003_alter_loandata_monthly_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
