# Generated by Django 5.0.6 on 2024-07-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pancard', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pincode', models.CharField(max_length=10)),
                ('education', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=20)),
            ],
        ),
    ]
